/* eslint-disable */
// Necessary to disable esLint for some stuff which would require too much code to fix (like last commas in objects)
<%
// List of props used in the template
var modals = props.modals
var initialState = props.initialState
%>

import { createReducer, createActions } from 'reduxsauce'
import Immutable from 'seamless-immutable'

/* ------------- Types and Action Creators ------------- */

let MainTypes = {}
let MainCreators = {}

/* AUTOGENERATED BLOC START */
let createdActions
<% for (let modal of modals) { %>
  createdActions = createActions({
    toggle<%= modal.Name %>ModalRequest: [],
    toggle<%= modal.Name %>ModalSuccess: [],
    toggle<%= modal.Name %>ModalFailure: [],
  })

  MainTypes = {...createdActions.Types, ...MainTypes}
  MainCreators = {...createdActions.Creators, ...MainCreators}
<% } %>

/* AUTOGENERATED BLOC END */
export const ModalsTypes = MainTypes
export default MainCreators


/* ------------- Initial State ------------- */

export const INITIAL_STATE = Immutable(<%- initialState %>)

/* ------------- Reducers ------------- */

const reducers = {}
/* AUTOGENERATED BLOC START */

<% for (let modal of modals) { %>
  export const toggle<%- modal.Name %>ModalRequest = state => state
  export const toggle<%- modal.Name %>ModalFailure = state => state
  export const toggle<%- modal.Name %>ModalSuccess = state => state.merge({ show<%- modal.Name %>Modal: !state.show<%- modal.Name %>Modal })

  reducers = {
    [ModalsTypes.TOGGLE_<%- modal.NAME %>_MODAL_REQUEST]: toggle<%- modal.Name %>ModalRequest,
    [ModalsTypes.TOGGLE_<%- modal.NAME %>_MODAL_SUCCESS]: toggle<%- modal.Name %>ModalSuccess,
    [ModalsTypes.TOGGLE_<%- modal.NAME %>_MODAL_FAILURE]: toggle<%- modal.Name %>ModalFailure,
    ...reducers
  }
<% } %>

/* AUTOGENERATED BLOC END */

/* ------------- Hookup Reducers To Types ------------- */
export const reducer = createReducer(INITIAL_STATE, reducers)
