/* eslint-disable */
// Necessary to disable esLint for some stuff which would require too much code to fix (like last commas in objects)
<%
// List of props used in the template
var modals = props.modals
var initialState = props.initialState
%>

import { createReducer, createActions } from 'reduxsauce'
import Immutable from 'seamless-immutable'

/* ------------- Types and Action Creators ------------- */

let MainTypes = {}
let MainCreators = {}

/* AUTOGENERATED BLOC START */
let createdActions
<% for (let modal of modals) { %>
  createdActions = createActions({
    toggle<%= modal.Name %>Modal: ['params'],
    open<%= modal.Name %>Modal: ['params'],
    close<%= modal.Name %>Modal: ['params'],
  })

  MainTypes = {
    TOGGLE_<%-  modal.NAME %>_MODAL: 'TOGGLE_<%- modal.NAME %>_MODAL', 
    OPEN_<%-    modal.NAME %>_MODAL: 'OPEN_<%-   modal.NAME %>_MODAL', 
    CLOSE_<%-   modal.NAME %>_MODAL: 'CLOSE_<%-  modal.NAME %>_MODAL', 
    ...MainTypes}
  MainCreators = {...createdActions.Creators, ...MainCreators}
<% } %>

/* AUTOGENERATED BLOC END */
export const ModalsTypes = MainTypes
export default MainCreators


/* ------------- Initial State ------------- */

export const INITIAL_STATE = Immutable(<%- initialState %>)

/* ------------- Reducers ------------- */

const reducers = {}
/* AUTOGENERATED BLOC START */

<% for (let modal of modals) { %>
  export const toggle<%- modal.Name %>Modal = (state, action) => state.merge({
    <%- modal.name %>ModalParams: action.params || state.<%- modal.name %>ModalParams,
    show<%- modal.Name %>Modal: !state.show<%- modal.Name %>Modal 
  })
  export const open<%-   modal.Name %>Modal = (state, action) => state.merge({
    <%- modal.name %>ModalParams: action.params || state.<%- modal.name %>ModalParams,
    show<%- modal.Name %>Modal: true 
  })
  export const close<%-  modal.Name %>Modal = (state, action) => state.merge({ 
    <%- modal.name %>ModalParams: action.params || state.<%- modal.name %>ModalParams,
    show<%- modal.Name %>Modal: false 
  })

  reducers = {
    [ModalsTypes.TOGGLE_<%- modal.NAME %>_MODAL]: toggle<%- modal.Name %>Modal,
    [ModalsTypes.OPEN_<%-   modal.NAME %>_MODAL]: open<%-   modal.Name %>Modal,
    [ModalsTypes.CLOSE_<%-  modal.NAME %>_MODAL]: close<%-  modal.Name %>Modal,
    ...reducers
  }
<% } %>

/* AUTOGENERATED BLOC END */

/* ------------- Hookup Reducers To Types ------------- */
export const reducer = createReducer(INITIAL_STATE, reducers)
